# .github/workflows/unzip_debug.yml

name: Debug Unzip File to Root Directory

on:
  push:
    branches:
      - main  # 根据需要修改分支名称

jobs:
  unzip_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 拉取代码库
        with:
          fetch-depth: 0  # 确保完整拉取，避免文件丢失

      - name: Verify file existence in root directory
        run: |
          echo "Checking if typecho (1).zip exists..."
          ls -al
          if [ -f "typecho (1).zip" ]; then
            echo "File found: typecho (1).zip"
          else
            echo "Error: typecho (1).zip not found!"
            exit 1
          fi

      - name: Unzip typecho (1).zip to root directory
        run: |
          echo "Unzipping file..."
          unzip "typecho (1).zip" -d .
          echo "Unzip completed."

      - name: List files after unzipping
        run: |
          echo "Contents of the directory after unzipping:"
          ls -al
