# .github/workflows/unzip_debug.yml

name: Ensure File Unzips to Repository Root

on:
  push:
    branches:
      - main  # 可根据需要修改分支名称

jobs:
  unzip_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 完整拉取代码库

      - name: Print working directory and list files
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files in the current directory:"
          ls -al

      - name: Unzip typecho (1).zip and place content in root
        run: |
          # 创建临时解压目录
          echo "Creating temporary directory for unzipping..."
          mkdir temp_unzip
          echo "Unzipping typecho (1).zip into temporary directory..."
          unzip "typecho (1).zip" -d temp_unzip

          # 将解压后的内容移动到根目录
          echo "Moving unzipped content to repository root..."
          mv temp_unzip/* .

          # 清理临时目录
          echo "Cleaning up temporary directory..."
          rm -rf temp_unzip

      - name: List files after unzipping
        run: |
          echo "Contents of the repository after unzipping:"
          ls -al
