# .github/workflows/unzip_to_root.yml

name: Unzip file to root directory and sync

on:
  push:
    branches:
      - main  # 替换为你使用的分支名称

jobs:
  unzip_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整代码库历史

      - name: Print working directory and list initial files
        run: |
          echo "Current directory:"
          pwd
          echo "Files before unzip:"
          ls -al

      - name: Unzip typecho (1).zip and move files to root
        run: |
          echo "Creating temporary directory for unzip..."
          mkdir temp_unzip
          
          echo "Unzipping typecho (1).zip into temporary directory..."
          unzip "typecho (1).zip" -d temp_unzip

          echo "Moving all unzipped files to root directory..."
          mv temp_unzip/* .

          echo "Cleaning up temporary directory..."
          rm -rf temp_unzip

          echo "Files after unzip and move:"
          ls -al

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

          # 检查变动并提交
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected. Committing and pushing..."
            git add .
            git commit -m "Unzipped typecho (1).zip to root directory [skip ci]"
            git push origin ${{ github.ref_name }}
          else
            echo "No changes to commit."
          fi
